fix sonar issues
Gamify-IT/crosswordpuzzle pull request #43
Opened 2023-04-16 14:54 UTC by Gr33ndev

Part of https://github.com/Gamify-IT/issues/issues/498

https://sonar.sqa-kube-cluster4.cloudns.nz/dashboard?id=crosswordpuzzle

**Please test is everything is still working as intendet**

2023-04-16 19:19 UTC, madebyTimo requested changes
good work except for the one function

2023-04-16 19:19 UTC, madebyTimo commented on src/components/InputField.vue
> +  //NOSONAR
I think line 63 to 76 of this function are useless and can be removed.

Maybe then it is also possible to not use `NOSONAR`

2023-04-18 11:37 UTC, delvh commented on src/views/CrosswordpuzzleView.vue
> +  //NOSONAR
why exactly?

2023-04-18 11:37 UTC, delvh commented on src/views/CrosswordpuzzleView.vue
> +  //NOSONAR
Because this function is too large?
The better alternative would be to extract subfunctions.

2023-04-26 17:19 UTC, Gr33ndev commented
Closed, because in the next sprint there will be big all-encompassing changes and it will be easier to fix the then new sonar issues.

2023-04-26 17:19 UTC, Gr33ndev commented
Wrong PR

2023-04-30 13:43 UTC, delvh approved these changes
Should work.
The cyclomatic complexity problems were not tackled, but we can leave that for another PR.

2023-05-04 14:48 UTC, merged